name: vl-haskell
version: 0.1.0
author: Christoph Finkensiep
copyright: 2020 Christoph Finkensiep
license: BSD3
license-file: LICENSE

data-dir: data

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - Chart
  - Chart-cairo
  - colour
  - containers
  - data-default
  - deepseq
  # - diagrams-lib
  # - diagrams-svg
  - directory
  - filepath
  - ghc
  - hashable
  - HCodecs
  - lens
  - lilypond
  - loop
  - machines
  - math-functions >= 0.3.3.0
  - memoize
  - mtl
  - mwc-random
  - palette
  # - plots
  - prettify
  - primitive
  - process
  - streamly
  - temporary
  - terminal-progress-bar
  - text
  - transformers
  - vector
  
library:
  source-dirs:
    - src
  other-modules:
    - VoiceLeading.IO.HorizontalBars

ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]

executables:

  vl-haskell-exe:
    source-dirs: [app]
    main: Main.hs
    other-modules: []
    dependencies:
      - vl-haskell
      - clock
      - formatting
      - optparse-applicative
      - yaml

  vl-train:
    source-dirs: [app/train]
    main: train.hs
    dependencies:
      - vl-haskell
      - clock
      - formatting
      - optparse-applicative

  vl-compose:
    source-dirs: [app/compose]
    main: compose.hs
    dependencies:
      - vl-haskell
      - optparse-applicative
      - yaml

  vl-view-model:
    source-dirs: [app/view-model]
    main: view-model.hs
    dependencies:
      - vl-haskell
      - optparse-applicative

  vl-rate:
    source-dirs: [app/rate]
    main: rate.hs
    dependencies:
      - vl-haskell
      - optparse-applicative
    

tests:
  vl-haskell-test:
    source-dirs: [test]
    main: Spec.hs
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  
